{% set name = "compas_timber" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/compas_timber-{{ version }}.tar.gz
  sha256: 007383420ddc6478b06cc10af8523d9a08b72667f7dd299d8e633cd3dfc3acfd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - rtree
    - compas >=2.0,<3

test:
  imports:
    - compas_timber
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gramaziokohler/compas_timber
  summary: COMPAS package for modeling, designing and fabricating timber assemblies.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chenkasirer
    - gonzalocasas
