{% set name = "compas_timber" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/compas_timber-{{ version }}.tar.gz
  sha256: 97aa426df42ef17d9eae445fb8a60435d469c067f2a996c6acca41ce6fa4e154

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - rtree
    - compas >=2.0,<3
    - compas_model ==0.4.4

test:
  imports:
    - compas_timber
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gramaziokohler/compas_timber
  summary: COMPAS package for modeling, designing and fabricating timber assemblies.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chenkasirer
    - gonzalocasas
