{% set name = "compas_timber" %}
{% set version = "0.15.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/compas_timber-{{ version }}.tar.gz
  sha256: 205ea57e9a0b8b41ed4670d73b9a0ebbb1e6d0707956a763985848fdfb85a77b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - rtree
    - compas >=2.0,<3
    - compas_model ==0.4.4

test:
  imports:
    - compas_timber
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/gramaziokohler/compas_timber
  summary: COMPAS package for modeling, designing and fabricating timber assemblies.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chenkasirer
    - gonzalocasas
